# Generated by Django 4.2.2 on 2023-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_generatedfile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefile',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
