# Generated by Django 4.2.2 on 2023-07-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_templatefile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
