# Generated by Django 4.2.2 on 2023-07-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_templatefile_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefile',
            name='timestamp',
        ),
    ]
